### ISSUE TITLE
cannot install on Ubuntu 20.04 

### ISSUE THREAD

**Issue by michelvankessel** [provable-things/ptokens.js-v1#2]
Can you please check the following errors during install? 

npm install ptokens

19 verbose stack Error: Refusing to install package with name "ptokens" under a package
19 verbose stack also called "ptokens". Did you name your project the same
19 verbose stack as the dependency you're installing?
19 verbose stack
19 verbose stack For more information, see:
19 verbose stack     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
19 verbose stack     at checkSelf (/usr/lib/node_modules/npm/lib/install/validate-args.js:75:14)
19 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
19 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
19 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
19 verbose stack     at hasMinimumFields (/usr/lib/node_modules/npm/lib/install/validate-args.js:30:12)
19 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
19 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
19 verbose stack     at chain (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
19 verbose stack     at /usr/lib/node_modules/npm/lib/install/validate-args.js:16:5
19 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
19 verbose stack     at Array.forEach (<anonymous>)
19 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
19 verbose stack     at Array.forEach (<anonymous>)
19 verbose stack     at asyncMap (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
19 verbose stack     at module.exports (/usr/lib/node_modules/npm/lib/install/validate-args.js:15:3)
19 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
20 verbose cwd /home/michel/development/ptokens.js
21 verbose Linux 4.19.104-microsoft-standard
22 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "ptokens"
23 verbose node v14.4.0
24 verbose npm  v6.14.5
25 error code ENOSELF
26 error Refusing to install package with name "ptokens" under a package
26 error also called "ptokens". Did you name your project the same
26 error as the dependency you're installing?
26 error
26 error For more information, see:
26 error     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
27 verbose exit [ 1, true ]

**Comment by allemanfredi** [comment]
Hello @michelvankessel, are you naming your project the same as the dependency you're installing? If so, you could need to change your project name within the `package.json` file.
