### ISSUE TITLE
pERC20 requires tokenAddress by declaration though it's not used in class

### ISSUE THREAD

**Issue by Lebed-kun** [provable-things/ptokens.js-v1#5]
tokenAddress is declared here: https://github.com/provable-things/ptokens.js/blob/master/packages/ptokens-perc20/types/index.d.ts

But is not used here: https://github.com/provable-things/ptokens.js/blob/master/packages/ptokens-perc20/src/index.js

What's purpose of tokenAddress though?

**Comment by allemanfredi** [comment]
Hello @Lebed-kun, there shouldn't be, thanks for bringing it back! Fixed [here](https://github.com/provable-things/ptokens.js/commit/ef3d18dc45a242974983e37f3a4cdbc4506f597c).
