### ISSUE TITLE
Feature Request: Add memo to EOS tokens transactions.

### ISSUE THREAD

**Issue by djmbritt** [provable-things/ptokens.js-v1#9]
Hi there, 

I'm with the Effect Network team, last year together with pTokens we published EFX on Binance Smart Chain. 
It's been good and everything is working great. 
But we stumbled on an issue, and we wonder if you could implement a feature for us. 

When making transactions on EOS, users can submit a memo with every transaction. 
This is useful for identifying incoming transactions and delegating the funds to the appropriate user in a smart contract.

We want users to be able to do this as well when making a transaction from BSC to EOS.

It can be seen here: https://github.com/provable-things/ptokens.js/blob/3efaee81cb2c9aad34de17cd1c2d5e16e3bc26f9/packages/ptokens-peosio-token/src/index.js#L132
When tokens are issued, a memo is passed. 

Is it possible to pass a `memo` when using the `redeem` method? 
When a transaction is done from BSC to EOS a `memo` is passed to the function, and picked up on the EOS side for the transaction that is made for the user. 

I wouldn't mind taking a look at the source code myself and making a pull request to do it. I would appreciate some help though if you could point me in the right direction.

**Comment by oliviera9** [comment]
Hello @djmbritt,
we are already working on passing metadata while redeeming tokens from EVM (https://github.com/provable-things/ptokens.js/commit/d549fc3c24f94585cdc07caaa3bdedc386d5b44e).
That metadata would be an argument of the `pegout` EOS action. Would this suit your needs?

**Comment by djmbritt** [comment]
Hi @oliviera9,

As long as we can pass a string in the metadata that should work well for our purposes!
That does seem to be the case :)
Looking forward to implementing this soon.
Thank you! : 🙏

**Comment by djmbritt** [comment]
Do you have a timeframe when this will become available?
Otherwise we'll test with the commit you provided.

**Comment by oliviera9** [comment]
> Do you have a timeframe when this will become available? Otherwise we'll test with the commit you provided.

We may merge that commit and release a new version next week.

**Comment by djmbritt** [comment]
Looking forward to it :)

**Comment by djmbritt** [comment]
Any updates on this?

**Comment by oliviera9** [comment]
@djmbritt sorry for the delay. We encountered an issue when merging the dev-branch. We are working on it.

**Comment by djmbritt** [comment]
Okay, hope it y'all manage with it.
Thanks for the response.

**Comment by oliviera9** [comment]
@djmbritt The commit https://github.com/provable-things/ptokens.js/commit/d549fc3c24f94585cdc07caaa3bdedc386d5b44e I mentioned above is now merged in `master`, and available with the new release 0.15.0.

**Comment by djmbritt** [comment]
That's awesome, thank you.
